apiVersion: v1
kind: Service
metadata:
  name: {{ include "template-nf.name" . }}
  labels:
    {{- include "template-nf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "template-nf.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ default "TCP" .protocol }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
