/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
)



// IndividualPolicyControlEventsSubscriptionDocumentApiRouter defines the required methods for binding the api requests to a responses for the IndividualPolicyControlEventsSubscriptionDocumentApi
// The IndividualPolicyControlEventsSubscriptionDocumentApiRouter implementation should parse necessary information from the http request,
// pass the data to a IndividualPolicyControlEventsSubscriptionDocumentApiServicer to perform the required actions, then write the service results to the http response.
type IndividualPolicyControlEventsSubscriptionDocumentApiRouter interface { 
	DeletePcEventExposureSubsc(http.ResponseWriter, *http.Request)
	GetPcEventExposureSubsc(http.ResponseWriter, *http.Request)
	PutPcEventExposureSubsc(http.ResponseWriter, *http.Request)
}
// PolicyControlEventsSubscriptionCollectionApiRouter defines the required methods for binding the api requests to a responses for the PolicyControlEventsSubscriptionCollectionApi
// The PolicyControlEventsSubscriptionCollectionApiRouter implementation should parse necessary information from the http request,
// pass the data to a PolicyControlEventsSubscriptionCollectionApiServicer to perform the required actions, then write the service results to the http response.
type PolicyControlEventsSubscriptionCollectionApiRouter interface { 
	PostPcEventExposureSubsc(http.ResponseWriter, *http.Request)
}


// IndividualPolicyControlEventsSubscriptionDocumentApiServicer defines the api actions for the IndividualPolicyControlEventsSubscriptionDocumentApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type IndividualPolicyControlEventsSubscriptionDocumentApiServicer interface { 
	DeletePcEventExposureSubsc(context.Context, string) (ImplResponse, error)
	GetPcEventExposureSubsc(context.Context, string) (ImplResponse, error)
	PutPcEventExposureSubsc(context.Context, string, PcEventExposureSubsc) (ImplResponse, error)
}


// PolicyControlEventsSubscriptionCollectionApiServicer defines the api actions for the PolicyControlEventsSubscriptionCollectionApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type PolicyControlEventsSubscriptionCollectionApiServicer interface { 
	PostPcEventExposureSubsc(context.Context, PcEventExposureSubsc) (ImplResponse, error)
}
