/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// IndividualPolicyControlEventsSubscriptionDocumentApiController binds http requests to an api service and writes the service results to the http response
type IndividualPolicyControlEventsSubscriptionDocumentApiController struct {
	service IndividualPolicyControlEventsSubscriptionDocumentApiServicer
	errorHandler ErrorHandler
}

// IndividualPolicyControlEventsSubscriptionDocumentApiOption for how the controller is set up.
type IndividualPolicyControlEventsSubscriptionDocumentApiOption func(*IndividualPolicyControlEventsSubscriptionDocumentApiController)

// WithIndividualPolicyControlEventsSubscriptionDocumentApiErrorHandler inject ErrorHandler into controller
func WithIndividualPolicyControlEventsSubscriptionDocumentApiErrorHandler(h ErrorHandler) IndividualPolicyControlEventsSubscriptionDocumentApiOption {
	return func(c *IndividualPolicyControlEventsSubscriptionDocumentApiController) {
		c.errorHandler = h
	}
}

// NewIndividualPolicyControlEventsSubscriptionDocumentApiController creates a default api controller
func NewIndividualPolicyControlEventsSubscriptionDocumentApiController(s IndividualPolicyControlEventsSubscriptionDocumentApiServicer, opts ...IndividualPolicyControlEventsSubscriptionDocumentApiOption) Router {
	controller := &IndividualPolicyControlEventsSubscriptionDocumentApiController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the IndividualPolicyControlEventsSubscriptionDocumentApiController
func (c *IndividualPolicyControlEventsSubscriptionDocumentApiController) Routes() Routes {
	return Routes{ 
		{
			"DeletePcEventExposureSubsc",
			strings.ToUpper("Delete"),
			"/npcf-eventexposure/v1/subscriptions/{subscriptionId}",
			c.DeletePcEventExposureSubsc,
		},
		{
			"GetPcEventExposureSubsc",
			strings.ToUpper("Get"),
			"/npcf-eventexposure/v1/subscriptions/{subscriptionId}",
			c.GetPcEventExposureSubsc,
		},
		{
			"PutPcEventExposureSubsc",
			strings.ToUpper("Put"),
			"/npcf-eventexposure/v1/subscriptions/{subscriptionId}",
			c.PutPcEventExposureSubsc,
		},
	}
}

// DeletePcEventExposureSubsc - Cancels an existing Individual Policy Control Events Subscription 
func (c *IndividualPolicyControlEventsSubscriptionDocumentApiController) DeletePcEventExposureSubsc(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	subscriptionIdParam := params["subscriptionId"]
	
	result, err := c.service.DeletePcEventExposureSubsc(r.Context(), subscriptionIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// GetPcEventExposureSubsc - Reads an existing Individual Policy Control Events Subscription
func (c *IndividualPolicyControlEventsSubscriptionDocumentApiController) GetPcEventExposureSubsc(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	subscriptionIdParam := params["subscriptionId"]
	
	result, err := c.service.GetPcEventExposureSubsc(r.Context(), subscriptionIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// PutPcEventExposureSubsc - Modifies an existing Individual Policy Control Events Subscription 
func (c *IndividualPolicyControlEventsSubscriptionDocumentApiController) PutPcEventExposureSubsc(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	subscriptionIdParam := params["subscriptionId"]
	
	pcEventExposureSubscParam := PcEventExposureSubsc{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&pcEventExposureSubscParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertPcEventExposureSubscRequired(pcEventExposureSubscParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.PutPcEventExposureSubsc(r.Context(), subscriptionIdParam, pcEventExposureSubscParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}
