/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"
)

// PolicyControlEventsSubscriptionCollectionApiController binds http requests to an api service and writes the service results to the http response
type PolicyControlEventsSubscriptionCollectionApiController struct {
	service PolicyControlEventsSubscriptionCollectionApiServicer
	errorHandler ErrorHandler
}

// PolicyControlEventsSubscriptionCollectionApiOption for how the controller is set up.
type PolicyControlEventsSubscriptionCollectionApiOption func(*PolicyControlEventsSubscriptionCollectionApiController)

// WithPolicyControlEventsSubscriptionCollectionApiErrorHandler inject ErrorHandler into controller
func WithPolicyControlEventsSubscriptionCollectionApiErrorHandler(h ErrorHandler) PolicyControlEventsSubscriptionCollectionApiOption {
	return func(c *PolicyControlEventsSubscriptionCollectionApiController) {
		c.errorHandler = h
	}
}

// NewPolicyControlEventsSubscriptionCollectionApiController creates a default api controller
func NewPolicyControlEventsSubscriptionCollectionApiController(s PolicyControlEventsSubscriptionCollectionApiServicer, opts ...PolicyControlEventsSubscriptionCollectionApiOption) Router {
	controller := &PolicyControlEventsSubscriptionCollectionApiController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the PolicyControlEventsSubscriptionCollectionApiController
func (c *PolicyControlEventsSubscriptionCollectionApiController) Routes() Routes {
	return Routes{ 
		{
			"PostPcEventExposureSubsc",
			strings.ToUpper("Post"),
			"/npcf-eventexposure/v1/subscriptions",
			c.PostPcEventExposureSubsc,
		},
	}
}

// PostPcEventExposureSubsc - Creates a new Individual Policy Control Events Subscription resource
func (c *PolicyControlEventsSubscriptionCollectionApiController) PostPcEventExposureSubsc(w http.ResponseWriter, r *http.Request) {
	pcEventExposureSubscParam := PcEventExposureSubsc{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&pcEventExposureSubscParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertPcEventExposureSubscRequired(pcEventExposureSubscParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.PostPcEventExposureSubsc(r.Context(), pcEventExposureSubscParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}
