/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// PolicyControlEventsSubscriptionCollectionApiService is a service that implements the logic for the PolicyControlEventsSubscriptionCollectionApiServicer
// This service should implement the business logic for every endpoint for the PolicyControlEventsSubscriptionCollectionApi API.
// Include any external packages or services that will be required by this service.
type PolicyControlEventsSubscriptionCollectionApiService struct {
}

// NewPolicyControlEventsSubscriptionCollectionApiService creates a default api service
func NewPolicyControlEventsSubscriptionCollectionApiService() PolicyControlEventsSubscriptionCollectionApiServicer {
	return &PolicyControlEventsSubscriptionCollectionApiService{}
}

// PostPcEventExposureSubsc - Creates a new Individual Policy Control Events Subscription resource
func (s *PolicyControlEventsSubscriptionCollectionApiService) PostPcEventExposureSubsc(ctx context.Context, pcEventExposureSubsc PcEventExposureSubsc) (ImplResponse, error) {
	// TODO - update PostPcEventExposureSubsc with the required logic for this service method.
	// Add api_policy_control_events_subscription_collection_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(201, PcEventExposureSubsc{}) or use other options such as http.Ok ...
	//return Response(201, PcEventExposureSubsc{}), nil

	//TODO: Uncomment the next line to return response Response(400, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(400, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(401, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(401, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(403, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(403, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(404, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(411, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(411, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(413, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(413, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(415, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(415, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(429, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(429, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(500, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(500, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(502, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(502, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(503, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(503, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(0, {}) or use other options such as http.Ok ...
	//return Response(0, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("PostPcEventExposureSubsc method not implemented")
}
