/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AnGwAddress - Describes the address of the access network gateway control node.
type AnGwAddress struct {

	// String identifying a IPv4 address formatted in the 'dotted decimal' notation as defined in RFC 1166. 
	AnGwIpv4Addr string `json:"anGwIpv4Addr,omitempty"`

	AnGwIpv6Addr Ipv6Addr `json:"anGwIpv6Addr,omitempty"`
}

// AssertAnGwAddressRequired checks if the required fields are not zero-ed
func AssertAnGwAddressRequired(obj AnGwAddress) error {
	if err := AssertIpv6AddrRequired(obj.AnGwIpv6Addr); err != nil {
		return err
	}
	return nil
}

// AssertRecurseAnGwAddressRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AnGwAddress (e.g. [][]AnGwAddress), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAnGwAddressRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAnGwAddress, ok := obj.(AnGwAddress)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAnGwAddressRequired(aAnGwAddress)
	})
}
