/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// NoProfileMatchInfo - Provides the reason for not finding NF matching the search criteria
type NoProfileMatchInfo struct {

	Reason NoProfileMatchReason `json:"reason"`

	QueryParamCombinationList []QueryParamCombination `json:"queryParamCombinationList,omitempty"`
}

// AssertNoProfileMatchInfoRequired checks if the required fields are not zero-ed
func AssertNoProfileMatchInfoRequired(obj NoProfileMatchInfo) error {
	elements := map[string]interface{}{
		"reason": obj.Reason,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertNoProfileMatchReasonRequired(obj.Reason); err != nil {
		return err
	}
	for _, el := range obj.QueryParamCombinationList {
		if err := AssertQueryParamCombinationRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseNoProfileMatchInfoRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of NoProfileMatchInfo (e.g. [][]NoProfileMatchInfo), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseNoProfileMatchInfoRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aNoProfileMatchInfo, ok := obj.(NoProfileMatchInfo)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertNoProfileMatchInfoRequired(aNoProfileMatchInfo)
	})
}
