/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Failure - Represents the failure reason for the unsuccessful result.   Possible values are: - UNSPECIFIED: Indicates the PCF received the UE sent UE policy delivery service cause #111   (Protocol error, unspecified). - UE_NOT_REACHABLE: Indicates the PCF received the notification from the AMF that the UE is   not reachable. - UNKNOWN: Indicates unknown reasons upon no response from the UE, e.g. UPDS message type is   not defined or not implemented by the UE, or not compatible with the UPDS state, in which   the UE shall ignore the UPDS message. - UE_TEMP_UNREACHABLE: Indicates the PCF received the notification from the AMF that the UE   is not reachable but the PCF will retry again. 
type Failure struct {
}

// AssertFailureRequired checks if the required fields are not zero-ed
func AssertFailureRequired(obj Failure) error {
	return nil
}

// AssertRecurseFailureRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Failure (e.g. [][]Failure), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseFailureRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aFailure, ok := obj.(Failure)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertFailureRequired(aFailure)
	})
}
