/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RatTypeAnyOf string

// List of RatTypeAnyOf
const (
	NR RatTypeAnyOf = "NR"
	EUTRA RatTypeAnyOf = "EUTRA"
	WLAN RatTypeAnyOf = "WLAN"
	VIRTUAL RatTypeAnyOf = "VIRTUAL"
	NBIOT RatTypeAnyOf = "NBIOT"
	WIRELINE RatTypeAnyOf = "WIRELINE"
	WIRELINE_CABLE RatTypeAnyOf = "WIRELINE_CABLE"
	WIRELINE_BBF RatTypeAnyOf = "WIRELINE_BBF"
	LTE_M RatTypeAnyOf = "LTE-M"
	NR_U RatTypeAnyOf = "NR_U"
	EUTRA_U RatTypeAnyOf = "EUTRA_U"
	TRUSTED_N3_GA RatTypeAnyOf = "TRUSTED_N3GA"
	TRUSTED_WLAN RatTypeAnyOf = "TRUSTED_WLAN"
	UTRA RatTypeAnyOf = "UTRA"
	GERA RatTypeAnyOf = "GERA"
	NR_LEO RatTypeAnyOf = "NR_LEO"
	NR_MEO RatTypeAnyOf = "NR_MEO"
	NR_GEO RatTypeAnyOf = "NR_GEO"
	NR_OTHER_SAT RatTypeAnyOf = "NR_OTHER_SAT"
	NR_REDCAP RatTypeAnyOf = "NR_REDCAP"
	WB_E_UTRAN_LEO RatTypeAnyOf = "WB_E_UTRAN_LEO"
	WB_E_UTRAN_MEO RatTypeAnyOf = "WB_E_UTRAN_MEO"
	WB_E_UTRAN_GEO RatTypeAnyOf = "WB_E_UTRAN_GEO"
	WB_E_UTRAN_OTHERSAT RatTypeAnyOf = "WB_E_UTRAN_OTHERSAT"
	NB_IOT_LEO RatTypeAnyOf = "NB_IOT_LEO"
	NB_IOT_MEO RatTypeAnyOf = "NB_IOT_MEO"
	NB_IOT_GEO RatTypeAnyOf = "NB_IOT_GEO"
	NB_IOT_OTHERSAT RatTypeAnyOf = "NB_IOT_OTHERSAT"
	LTE_M_LEO RatTypeAnyOf = "LTE_M_LEO"
	LTE_M_MEO RatTypeAnyOf = "LTE_M_MEO"
	LTE_M_GEO RatTypeAnyOf = "LTE_M_GEO"
	LTE_M_OTHERSAT RatTypeAnyOf = "LTE_M_OTHERSAT"
	NR_EREDCAP RatTypeAnyOf = "NR_EREDCAP"
)

// AssertRatTypeAnyOfRequired checks if the required fields are not zero-ed
func AssertRatTypeAnyOfRequired(obj RatTypeAnyOf) error {
	return nil
}

// AssertRecurseRatTypeAnyOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of RatTypeAnyOf (e.g. [][]RatTypeAnyOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseRatTypeAnyOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aRatTypeAnyOf, ok := obj.(RatTypeAnyOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertRatTypeAnyOfRequired(aRatTypeAnyOf)
	})
}
