/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type BufferedNotificationsActionAnyOf string

// List of BufferedNotificationsActionAnyOf
const (
	SEND_ALL BufferedNotificationsActionAnyOf = "SEND_ALL"
	DISCARD_ALL BufferedNotificationsActionAnyOf = "DISCARD_ALL"
	DROP_OLD BufferedNotificationsActionAnyOf = "DROP_OLD"
)

// AssertBufferedNotificationsActionAnyOfRequired checks if the required fields are not zero-ed
func AssertBufferedNotificationsActionAnyOfRequired(obj BufferedNotificationsActionAnyOf) error {
	return nil
}

// AssertRecurseBufferedNotificationsActionAnyOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of BufferedNotificationsActionAnyOf (e.g. [][]BufferedNotificationsActionAnyOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseBufferedNotificationsActionAnyOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aBufferedNotificationsActionAnyOf, ok := obj.(BufferedNotificationsActionAnyOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertBufferedNotificationsActionAnyOfRequired(aBufferedNotificationsActionAnyOf)
	})
}
