/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PcEventAnyOf string

// List of PcEventAnyOf
const (
	AC_TY_CH PcEventAnyOf = "AC_TY_CH"
	PLMN_CH PcEventAnyOf = "PLMN_CH"
	SAC_CH PcEventAnyOf = "SAC_CH"
	SAT_CATEGORY_CH PcEventAnyOf = "SAT_CATEGORY_CH"
	SUCCESS_UE_POL_DEL_SP PcEventAnyOf = "SUCCESS_UE_POL_DEL_SP"
	UNSUCCESS_UE_POL_DEL_SP PcEventAnyOf = "UNSUCCESS_UE_POL_DEL_SP"
	APPLICATION_START PcEventAnyOf = "APPLICATION_START"
	APPLICATION_STOP PcEventAnyOf = "APPLICATION_STOP"
)

// AssertPcEventAnyOfRequired checks if the required fields are not zero-ed
func AssertPcEventAnyOfRequired(obj PcEventAnyOf) error {
	return nil
}

// AssertRecursePcEventAnyOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PcEventAnyOf (e.g. [][]PcEventAnyOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePcEventAnyOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPcEventAnyOf, ok := obj.(PcEventAnyOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPcEventAnyOfRequired(aPcEventAnyOf)
	})
}
