/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SatelliteBackhaulCategoryAnyOf string

// List of SatelliteBackhaulCategoryAnyOf
const (
	GEO SatelliteBackhaulCategoryAnyOf = "GEO"
	MEO SatelliteBackhaulCategoryAnyOf = "MEO"
	LEO SatelliteBackhaulCategoryAnyOf = "LEO"
	OTHER_SAT SatelliteBackhaulCategoryAnyOf = "OTHER_SAT"
	DYNAMIC_GEO SatelliteBackhaulCategoryAnyOf = "DYNAMIC_GEO"
	DYNAMIC_MEO SatelliteBackhaulCategoryAnyOf = "DYNAMIC_MEO"
	DYNAMIC_LEO SatelliteBackhaulCategoryAnyOf = "DYNAMIC_LEO"
	DYNAMIC_OTHER_SAT SatelliteBackhaulCategoryAnyOf = "DYNAMIC_OTHER_SAT"
	NON_SATELLITE SatelliteBackhaulCategoryAnyOf = "NON_SATELLITE"
)

// AssertSatelliteBackhaulCategoryAnyOfRequired checks if the required fields are not zero-ed
func AssertSatelliteBackhaulCategoryAnyOfRequired(obj SatelliteBackhaulCategoryAnyOf) error {
	return nil
}

// AssertRecurseSatelliteBackhaulCategoryAnyOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of SatelliteBackhaulCategoryAnyOf (e.g. [][]SatelliteBackhaulCategoryAnyOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseSatelliteBackhaulCategoryAnyOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSatelliteBackhaulCategoryAnyOf, ok := obj.(SatelliteBackhaulCategoryAnyOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertSatelliteBackhaulCategoryAnyOfRequired(aSatelliteBackhaulCategoryAnyOf)
	})
}
