/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AccessType : Indicates whether the access is  via 3GPP or via non-3GPP.
type AccessType string

// List of AccessType
const (
	_3_GPP_ACCESS AccessType = "3GPP_ACCESS"
	NON_3_GPP_ACCESS AccessType = "NON_3GPP_ACCESS"
)

// AssertAccessTypeRequired checks if the required fields are not zero-ed
func AssertAccessTypeRequired(obj AccessType) error {
	return nil
}

// AssertRecurseAccessTypeRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AccessType (e.g. [][]AccessType), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAccessTypeRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAccessType, ok := obj.(AccessType)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAccessTypeRequired(aAccessType)
	})
}
