/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SubscriptionAction - Indicates the required action by the event producer NF on the event subscription if an exception occurs while the event is muted. 
type SubscriptionAction struct {
}

// AssertSubscriptionActionRequired checks if the required fields are not zero-ed
func AssertSubscriptionActionRequired(obj SubscriptionAction) error {
	return nil
}

// AssertRecurseSubscriptionActionRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of SubscriptionAction (e.g. [][]SubscriptionAction), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseSubscriptionActionRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSubscriptionAction, ok := obj.(SubscriptionAction)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertSubscriptionActionRequired(aSubscriptionAction)
	})
}
