/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// RatType - Indicates the radio access used.
type RatType struct {
}

// AssertRatTypeRequired checks if the required fields are not zero-ed
func AssertRatTypeRequired(obj RatType) error {
	return nil
}

// AssertRecurseRatTypeRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of RatType (e.g. [][]RatType), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseRatTypeRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aRatType, ok := obj.(RatType)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertRatTypeRequired(aRatType)
	})
}
