/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type NoProfileMatchReasonAnyOf string

// List of NoProfileMatchReasonAnyOf
const (
	REQUESTER_PLMN_NOT_ALLOWED NoProfileMatchReasonAnyOf = "REQUESTER_PLMN_NOT_ALLOWED"
	TARGET_NF_SUSPENDED NoProfileMatchReasonAnyOf = "TARGET_NF_SUSPENDED"
	TARGET_NF_UNDISCOVERABLE NoProfileMatchReasonAnyOf = "TARGET_NF_UNDISCOVERABLE"
	QUERY_PARAMS_COMBINATION_NO_MATCH NoProfileMatchReasonAnyOf = "QUERY_PARAMS_COMBINATION_NO_MATCH"
	TARGET_NF_TYPE_NOT_SUPPORTED NoProfileMatchReasonAnyOf = "TARGET_NF_TYPE_NOT_SUPPORTED"
	NO_PROFILE_MATCH_UNSPECIFIED NoProfileMatchReasonAnyOf = "UNSPECIFIED"
)

// AssertNoProfileMatchReasonAnyOfRequired checks if the required fields are not zero-ed
func AssertNoProfileMatchReasonAnyOfRequired(obj NoProfileMatchReasonAnyOf) error {
	return nil
}

// AssertRecurseNoProfileMatchReasonAnyOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of NoProfileMatchReasonAnyOf (e.g. [][]NoProfileMatchReasonAnyOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseNoProfileMatchReasonAnyOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aNoProfileMatchReasonAnyOf, ok := obj.(NoProfileMatchReasonAnyOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertNoProfileMatchReasonAnyOfRequired(aNoProfileMatchReasonAnyOf)
	})
}
