/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// EthernetFlowInfo - Identifies an UL/DL ethernet flow.
type EthernetFlowInfo struct {

	EthFlows []EthFlowDescription `json:"ethFlows,omitempty"`

	FlowNumber int32 `json:"flowNumber"`
}

// AssertEthernetFlowInfoRequired checks if the required fields are not zero-ed
func AssertEthernetFlowInfoRequired(obj EthernetFlowInfo) error {
	elements := map[string]interface{}{
		"flowNumber": obj.FlowNumber,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.EthFlows {
		if err := AssertEthFlowDescriptionRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseEthernetFlowInfoRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of EthernetFlowInfo (e.g. [][]EthernetFlowInfo), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseEthernetFlowInfoRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aEthernetFlowInfo, ok := obj.(EthernetFlowInfo)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertEthernetFlowInfoRequired(aEthernetFlowInfo)
	})
}
