/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// NotificationMethod - Represents the notification methods that can be subscribed.   Possible values are: - PERIODIC - ONE_TIME - ON_EVENT_DETECTION 
type NotificationMethod struct {
}

// AssertNotificationMethodRequired checks if the required fields are not zero-ed
func AssertNotificationMethodRequired(obj NotificationMethod) error {
	return nil
}

// AssertRecurseNotificationMethodRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of NotificationMethod (e.g. [][]NotificationMethod), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseNotificationMethodRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aNotificationMethod, ok := obj.(NotificationMethod)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertNotificationMethodRequired(aNotificationMethod)
	})
}
