/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SatelliteBackhaulCategory - Indicates the satellite backhaul used.
type SatelliteBackhaulCategory struct {
}

// AssertSatelliteBackhaulCategoryRequired checks if the required fields are not zero-ed
func AssertSatelliteBackhaulCategoryRequired(obj SatelliteBackhaulCategory) error {
	return nil
}

// AssertRecurseSatelliteBackhaulCategoryRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of SatelliteBackhaulCategory (e.g. [][]SatelliteBackhaulCategory), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseSatelliteBackhaulCategoryRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSatelliteBackhaulCategory, ok := obj.(SatelliteBackhaulCategory)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertSatelliteBackhaulCategoryRequired(aSatelliteBackhaulCategory)
	})
}
