/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// MutingNotificationsSettings - Indicates the Event producer NF settings to the Event consumer NF 
type MutingNotificationsSettings struct {

	MaxNoOfNotif int32 `json:"maxNoOfNotif,omitempty"`

	// indicating a time in seconds.
	DurationBufferedNotif int32 `json:"durationBufferedNotif,omitempty"`
}

// AssertMutingNotificationsSettingsRequired checks if the required fields are not zero-ed
func AssertMutingNotificationsSettingsRequired(obj MutingNotificationsSettings) error {
	return nil
}

// AssertRecurseMutingNotificationsSettingsRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of MutingNotificationsSettings (e.g. [][]MutingNotificationsSettings), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseMutingNotificationsSettingsRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aMutingNotificationsSettings, ok := obj.(MutingNotificationsSettings)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertMutingNotificationsSettingsRequired(aMutingNotificationsSettings)
	})
}
