/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PcEventExposureNotif - Represents notifications about Policy Control events related to an Individual Policy Events Subscription resource. 
type PcEventExposureNotif struct {

	NotifId string `json:"notifId"`

	EventNotifs []PcEventNotification `json:"eventNotifs"`
}

// AssertPcEventExposureNotifRequired checks if the required fields are not zero-ed
func AssertPcEventExposureNotifRequired(obj PcEventExposureNotif) error {
	elements := map[string]interface{}{
		"notifId": obj.NotifId,
		"eventNotifs": obj.EventNotifs,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.EventNotifs {
		if err := AssertPcEventNotificationRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecursePcEventExposureNotifRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PcEventExposureNotif (e.g. [][]PcEventExposureNotif), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePcEventExposureNotifRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPcEventExposureNotif, ok := obj.(PcEventExposureNotif)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPcEventExposureNotifRequired(aPcEventExposureNotif)
	})
}
