/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type FailureOneOf string

// List of FailureOneOf
const (
	FAILURE_UNSPECIFIED FailureOneOf = "UNSPECIFIED"
	UE_NOT_REACHABLE FailureOneOf = "UE_NOT_REACHABLE"
	UNKNOWN FailureOneOf = "UNKNOWN"
	UE_TEMP_UNREACHABLE FailureOneOf = "UE_TEMP_UNREACHABLE"
)

// AssertFailureOneOfRequired checks if the required fields are not zero-ed
func AssertFailureOneOfRequired(obj FailureOneOf) error {
	return nil
}

// AssertRecurseFailureOneOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of FailureOneOf (e.g. [][]FailureOneOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseFailureOneOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aFailureOneOf, ok := obj.(FailureOneOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertFailureOneOfRequired(aFailureOneOf)
	})
}
