/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SnssaiDnnCombination - Represents a combination of S-NSSAI and DNN(s).
type SnssaiDnnCombination struct {

	Snssai Snssai `json:"snssai,omitempty"`

	Dnns []string `json:"dnns,omitempty"`
}

// AssertSnssaiDnnCombinationRequired checks if the required fields are not zero-ed
func AssertSnssaiDnnCombinationRequired(obj SnssaiDnnCombination) error {
	if err := AssertSnssaiRequired(obj.Snssai); err != nil {
		return err
	}
	return nil
}

// AssertRecurseSnssaiDnnCombinationRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of SnssaiDnnCombination (e.g. [][]SnssaiDnnCombination), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseSnssaiDnnCombinationRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSnssaiDnnCombination, ok := obj.(SnssaiDnnCombination)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertSnssaiDnnCombinationRequired(aSnssaiDnnCombination)
	})
}
