/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AdditionalAccessInfo - Indicates the combination of additional Access Type and RAT Type for a MA PDU session. 
type AdditionalAccessInfo struct {

	AccessType AccessType `json:"accessType"`

	RatType RatType `json:"ratType,omitempty"`
}

// AssertAdditionalAccessInfoRequired checks if the required fields are not zero-ed
func AssertAdditionalAccessInfoRequired(obj AdditionalAccessInfo) error {
	elements := map[string]interface{}{
		"accessType": obj.AccessType,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertRatTypeRequired(obj.RatType); err != nil {
		return err
	}
	return nil
}

// AssertRecurseAdditionalAccessInfoRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AdditionalAccessInfo (e.g. [][]AdditionalAccessInfo), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAdditionalAccessInfoRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAdditionalAccessInfo, ok := obj.(AdditionalAccessInfo)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAdditionalAccessInfoRequired(aAdditionalAccessInfo)
	})
}
