/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// BufferedNotificationsAction - Indicates the required action by the event producer NF on the buffered Notifications. 
type BufferedNotificationsAction struct {
}

// AssertBufferedNotificationsActionRequired checks if the required fields are not zero-ed
func AssertBufferedNotificationsActionRequired(obj BufferedNotificationsAction) error {
	return nil
}

// AssertRecurseBufferedNotificationsActionRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of BufferedNotificationsAction (e.g. [][]BufferedNotificationsAction), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseBufferedNotificationsActionRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aBufferedNotificationsAction, ok := obj.(BufferedNotificationsAction)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertBufferedNotificationsActionRequired(aBufferedNotificationsAction)
	})
}
