/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// QueryParameter - Contains the name and value of a query parameter
type QueryParameter struct {

	Name string `json:"name"`

	Value string `json:"value"`
}

// AssertQueryParameterRequired checks if the required fields are not zero-ed
func AssertQueryParameterRequired(obj QueryParameter) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"value": obj.Value,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseQueryParameterRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of QueryParameter (e.g. [][]QueryParameter), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseQueryParameterRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aQueryParameter, ok := obj.(QueryParameter)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertQueryParameterRequired(aQueryParameter)
	})
}
