/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ServiceAreaCoverageInfo - It represents a list of Tracking Areas within a serving network.
type ServiceAreaCoverageInfo struct {

	// Indicates a list of Tracking Areas where the service is allowed.
	TacList []string `json:"tacList"`

	ServingNetwork PlmnIdNid `json:"servingNetwork,omitempty"`
}

// AssertServiceAreaCoverageInfoRequired checks if the required fields are not zero-ed
func AssertServiceAreaCoverageInfoRequired(obj ServiceAreaCoverageInfo) error {
	elements := map[string]interface{}{
		"tacList": obj.TacList,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertPlmnIdNidRequired(obj.ServingNetwork); err != nil {
		return err
	}
	return nil
}

// AssertRecurseServiceAreaCoverageInfoRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ServiceAreaCoverageInfo (e.g. [][]ServiceAreaCoverageInfo), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseServiceAreaCoverageInfoRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aServiceAreaCoverageInfo, ok := obj.(ServiceAreaCoverageInfo)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertServiceAreaCoverageInfoRequired(aServiceAreaCoverageInfo)
	})
}
