/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// NoProfileMatchReason - No Profile Match Reason
type NoProfileMatchReason struct {
}

// AssertNoProfileMatchReasonRequired checks if the required fields are not zero-ed
func AssertNoProfileMatchReasonRequired(obj NoProfileMatchReason) error {
	return nil
}

// AssertRecurseNoProfileMatchReasonRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of NoProfileMatchReason (e.g. [][]NoProfileMatchReason), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseNoProfileMatchReasonRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aNoProfileMatchReason, ok := obj.(NoProfileMatchReason)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertNoProfileMatchReasonRequired(aNoProfileMatchReason)
	})
}
