/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// QueryParamCombination - Contains a list of Query Parameters
type QueryParamCombination struct {

	QueryParams []QueryParameter `json:"queryParams"`
}

// AssertQueryParamCombinationRequired checks if the required fields are not zero-ed
func AssertQueryParamCombinationRequired(obj QueryParamCombination) error {
	elements := map[string]interface{}{
		"queryParams": obj.QueryParams,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.QueryParams {
		if err := AssertQueryParameterRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseQueryParamCombinationRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of QueryParamCombination (e.g. [][]QueryParamCombination), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseQueryParamCombinationRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aQueryParamCombination, ok := obj.(QueryParamCombination)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertQueryParamCombinationRequired(aQueryParamCombination)
	})
}
