/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PcEvent - Represents the policy control events that can be subscribed.
type PcEvent struct {
}

// AssertPcEventRequired checks if the required fields are not zero-ed
func AssertPcEventRequired(obj PcEvent) error {
	return nil
}

// AssertRecursePcEventRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PcEvent (e.g. [][]PcEvent), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePcEventRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPcEvent, ok := obj.(PcEvent)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPcEventRequired(aPcEvent)
	})
}
