/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// PcEventNotification - Represents the information reported for a Policy Control event.
type PcEventNotification struct {

	Event PcEvent `json:"event"`

	AccType AccessType `json:"accType,omitempty"`

	AddAccessInfo AdditionalAccessInfo `json:"addAccessInfo,omitempty"`

	RelAccessInfo AdditionalAccessInfo `json:"relAccessInfo,omitempty"`

	AnGwAddr AnGwAddress `json:"anGwAddr,omitempty"`

	RatType RatType `json:"ratType,omitempty"`

	PlmnId PlmnIdNid `json:"plmnId,omitempty"`

	SatBackhaulCategory SatelliteBackhaulCategory `json:"satBackhaulCategory,omitempty"`

	AppliedCov ServiceAreaCoverageInfo `json:"appliedCov,omitempty"`

	// String identifying a Supi that shall contain either an IMSI, a network specific identifier, a Global Cable Identifier (GCI) or a Global Line Identifier (GLI) as specified in clause  2.2A of 3GPP TS 23.003. It shall be formatted as follows  - for an IMSI \"imsi-<imsi>\", where <imsi> shall be formatted according to clause 2.2    of 3GPP TS 23.003 that describes an IMSI.  - for a network specific identifier \"nai-<nai>, where <nai> shall be formatted    according to clause 28.7.2 of 3GPP TS 23.003 that describes an NAI.  - for a GCI \"gci-<gci>\", where <gci> shall be formatted according to clause 28.15.2    of 3GPP TS 23.003.  - for a GLI \"gli-<gli>\", where <gli> shall be formatted according to clause 28.16.2 of    3GPP TS 23.003.To enable that the value is used as part of an URI, the string shall    only contain characters allowed according to the \"lower-with-hyphen\" naming convention    defined in 3GPP TS 29.501. 
	Supi string `json:"supi,omitempty"`

	// String identifying a Gpsi shall contain either an External Id or an MSISDN.  It shall be formatted as follows -External Identifier= \"extid-'extid', where 'extid'  shall be formatted according to clause 19.7.2 of 3GPP TS 23.003 that describes an  External Identifier.  
	Gpsi string `json:"gpsi,omitempty"`

	// string with format 'date-time' as defined in OpenAPI.
	TimeStamp time.Time `json:"timeStamp"`

	PduSessionInfo PduSessionInformation `json:"pduSessionInfo,omitempty"`

	// String providing an application identifier.
	AppId string `json:"appId,omitempty"`

	RepServices ServiceIdentification `json:"repServices,omitempty"`

	DelivFailure Failure `json:"delivFailure,omitempty"`
}

// AssertPcEventNotificationRequired checks if the required fields are not zero-ed
func AssertPcEventNotificationRequired(obj PcEventNotification) error {
	elements := map[string]interface{}{
		"event": obj.Event,
		"timeStamp": obj.TimeStamp,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertPcEventRequired(obj.Event); err != nil {
		return err
	}
	if err := AssertAdditionalAccessInfoRequired(obj.AddAccessInfo); err != nil {
		return err
	}
	if err := AssertAdditionalAccessInfoRequired(obj.RelAccessInfo); err != nil {
		return err
	}
	if err := AssertAnGwAddressRequired(obj.AnGwAddr); err != nil {
		return err
	}
	if err := AssertRatTypeRequired(obj.RatType); err != nil {
		return err
	}
	if err := AssertPlmnIdNidRequired(obj.PlmnId); err != nil {
		return err
	}
	if err := AssertSatelliteBackhaulCategoryRequired(obj.SatBackhaulCategory); err != nil {
		return err
	}
	if err := AssertServiceAreaCoverageInfoRequired(obj.AppliedCov); err != nil {
		return err
	}
	if err := AssertPduSessionInformationRequired(obj.PduSessionInfo); err != nil {
		return err
	}
	if err := AssertServiceIdentificationRequired(obj.RepServices); err != nil {
		return err
	}
	if err := AssertFailureRequired(obj.DelivFailure); err != nil {
		return err
	}
	return nil
}

// AssertRecursePcEventNotificationRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PcEventNotification (e.g. [][]PcEventNotification), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePcEventNotificationRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPcEventNotification, ok := obj.(PcEventNotification)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPcEventNotificationRequired(aPcEventNotification)
	})
}
