/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SubscriptionActionAnyOf string

// List of SubscriptionActionAnyOf
const (
	CLOSE SubscriptionActionAnyOf = "CLOSE"
	CONTINUE_WITH_MUTING SubscriptionActionAnyOf = "CONTINUE_WITH_MUTING"
	CONTINUE_WITHOUT_MUTING SubscriptionActionAnyOf = "CONTINUE_WITHOUT_MUTING"
)

// AssertSubscriptionActionAnyOfRequired checks if the required fields are not zero-ed
func AssertSubscriptionActionAnyOfRequired(obj SubscriptionActionAnyOf) error {
	return nil
}

// AssertRecurseSubscriptionActionAnyOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of SubscriptionActionAnyOf (e.g. [][]SubscriptionActionAnyOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseSubscriptionActionAnyOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSubscriptionActionAnyOf, ok := obj.(SubscriptionActionAnyOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertSubscriptionActionAnyOfRequired(aSubscriptionActionAnyOf)
	})
}
