/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type FlowDirectionAnyOf string

// List of FlowDirectionAnyOf
const (
	DOWNLINK FlowDirectionAnyOf = "DOWNLINK"
	UPLINK FlowDirectionAnyOf = "UPLINK"
	BIDIRECTIONAL FlowDirectionAnyOf = "BIDIRECTIONAL"
	FLOW_DIRECTION_UNSPECIFIED FlowDirectionAnyOf = "UNSPECIFIED"
)

// AssertFlowDirectionAnyOfRequired checks if the required fields are not zero-ed
func AssertFlowDirectionAnyOfRequired(obj FlowDirectionAnyOf) error {
	return nil
}

// AssertRecurseFlowDirectionAnyOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of FlowDirectionAnyOf (e.g. [][]FlowDirectionAnyOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseFlowDirectionAnyOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aFlowDirectionAnyOf, ok := obj.(FlowDirectionAnyOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertFlowDirectionAnyOfRequired(aFlowDirectionAnyOf)
	})
}
