/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type NotificationMethodAnyOf string

// List of NotificationMethodAnyOf
const (
	PERIODIC NotificationMethodAnyOf = "PERIODIC"
	ONE_TIME NotificationMethodAnyOf = "ONE_TIME"
	ON_EVENT_DETECTION NotificationMethodAnyOf = "ON_EVENT_DETECTION"
)

// AssertNotificationMethodAnyOfRequired checks if the required fields are not zero-ed
func AssertNotificationMethodAnyOfRequired(obj NotificationMethodAnyOf) error {
	return nil
}

// AssertRecurseNotificationMethodAnyOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of NotificationMethodAnyOf (e.g. [][]NotificationMethodAnyOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseNotificationMethodAnyOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aNotificationMethodAnyOf, ok := obj.(NotificationMethodAnyOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertNotificationMethodAnyOfRequired(aNotificationMethodAnyOf)
	})
}
