/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// IpFlowInfo - Identifies an UL/DL IP flow.
type IpFlowInfo struct {

	IpFlows []string `json:"ipFlows,omitempty"`

	FlowNumber int32 `json:"flowNumber"`
}

// AssertIpFlowInfoRequired checks if the required fields are not zero-ed
func AssertIpFlowInfoRequired(obj IpFlowInfo) error {
	elements := map[string]interface{}{
		"flowNumber": obj.FlowNumber,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseIpFlowInfoRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IpFlowInfo (e.g. [][]IpFlowInfo), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIpFlowInfoRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIpFlowInfo, ok := obj.(IpFlowInfo)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIpFlowInfoRequired(aIpFlowInfo)
	})
}
