/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// MutingExceptionInstructions - Indicates to an Event producer NF instructions for the subscription and stored events when an exception (e.g. full buffer) occurs at the Event producer NF while the event is muted. 
type MutingExceptionInstructions struct {

	BufferedNotifs BufferedNotificationsAction `json:"bufferedNotifs,omitempty"`

	Subscription SubscriptionAction `json:"subscription,omitempty"`
}

// AssertMutingExceptionInstructionsRequired checks if the required fields are not zero-ed
func AssertMutingExceptionInstructionsRequired(obj MutingExceptionInstructions) error {
	if err := AssertBufferedNotificationsActionRequired(obj.BufferedNotifs); err != nil {
		return err
	}
	if err := AssertSubscriptionActionRequired(obj.Subscription); err != nil {
		return err
	}
	return nil
}

// AssertRecurseMutingExceptionInstructionsRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of MutingExceptionInstructions (e.g. [][]MutingExceptionInstructions), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseMutingExceptionInstructionsRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aMutingExceptionInstructions, ok := obj.(MutingExceptionInstructions)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertMutingExceptionInstructionsRequired(aMutingExceptionInstructions)
	})
}
