/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ServiceIdentification - Identifies the service to which the subscription applies.
type ServiceIdentification struct {

	ServEthFlows []EthernetFlowInfo `json:"servEthFlows,omitempty"`

	ServIpFlows []IpFlowInfo `json:"servIpFlows,omitempty"`

	// Contains an AF application identifier.
	AfAppId string `json:"afAppId,omitempty"`
}

// AssertServiceIdentificationRequired checks if the required fields are not zero-ed
func AssertServiceIdentificationRequired(obj ServiceIdentification) error {
	for _, el := range obj.ServEthFlows {
		if err := AssertEthernetFlowInfoRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.ServIpFlows {
		if err := AssertIpFlowInfoRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseServiceIdentificationRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ServiceIdentification (e.g. [][]ServiceIdentification), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseServiceIdentificationRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aServiceIdentification, ok := obj.(ServiceIdentification)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertServiceIdentificationRequired(aServiceIdentification)
	})
}
