# SPDX-License-Identifier: MIT

global:
  kubernetesDistribution: Vanilla
  coreNetworkConfigMap: oai-5g-core-dev
  clusterIpServiceIpAllocation: true
  waitForNRF: true
  waitForUDR: true
  http2Param: "--http2-prior-knowledge"
  timeout: 2
  imagePullSecrets: []
  dev:
    rolloutNonce: "0"

mysql:
  enabled: true
  imagePullPolicy: IfNotPresent
  oai5gdatabase: basic
  imagePullSecrets: []
  persistence:
    enabled: false

ims:
  enabled: false

oai-nrf:
  enabled: true
  imagePullSecrets: []
  nfimage:
    repository: local/oai-nrf
    version: dev
    pullPolicy: Never
  config:
    logLevel: debug
  dev:
    rolloutNonce: "0"

oai-nssf:
  enabled: true
  imagePullSecrets: []
  nfimage:
    repository: local/oai-nssf
    version: dev
    pullPolicy: Never
  config:
    logLevel: debug
  dev:
    rolloutNonce: "0"

oai-lmf:
  enabled: true
  imagePullSecrets: []
  nfimage:
    repository: local/oai-lmf
    version: dev
    pullPolicy: Never
  dev:
    rolloutNonce: "0"

oai-udr:
  enabled: true
  imagePullSecrets: []
  nfimage:
    repository: local/oai-udr
    version: dev
    pullPolicy: Never
  start:
    udr: true
  dev:
    rolloutNonce: "0"

oai-udm:
  enabled: true
  imagePullSecrets: []
  nfimage:
    repository: local/oai-udm
    version: dev
    pullPolicy: Never
  dev:
    rolloutNonce: "0"

oai-ausf:
  enabled: true
  imagePullSecrets: []
  nfimage:
    repository: local/oai-ausf
    version: dev
    pullPolicy: Never
  dev:
    rolloutNonce: "0"

oai-amf:
  enabled: true
  imagePullSecrets: []
  nfimage:
    repository: local/oai-amf
    version: dev
    pullPolicy: Never
  multus:
    enabled: false
  dev:
    rolloutNonce: "0"

oai-smf:
  enabled: true
  imagePullSecrets: []
  nfimage:
    repository: local/oai-smf
    version: dev
    pullPolicy: Never
  multus:
    enabled: false
  config:
    imsHost: ""
  dev:
    rolloutNonce: "0"

oai-upf:
  enabled: true
  imagePullSecrets: []
  nfimage:
    repository: local/oai-upf
    version: dev
    pullPolicy: Never
  multus:
    enabled: false
  securityContext:
    privileged: true
  dev:
    rolloutNonce: "0"

oai-traffic-server:
  enabled: true
  imagePullSecrets: []
  nfimage:
    repository: local/oai-traffic-server
    version: dev
    pullPolicy: Never
  multus:
    enabled: false
  config:
    ueroute: 12.1.0.0/16
    upfHost: oai-upf
    noOfIperf3Server: 2
  dev:
    rolloutNonce: "0"

packetRusher:
  enabled: true
  amfNgap:
    serviceName: oai-amf-ngap
    service:
      type: NodePort
      port: 38412
      targetPort: 38412
      nodePort: 31412
