apiVersion: v1
kind: Service
metadata:
  name: oai-nwdaf-nbi-analytics
  namespace: oai-tutorial
  labels:
    project: oai-tutorial
    component: nwdaf-nbi-analytics
spec:
  ports:
  - port: 80
    targetPort: 8881
    protocol: TCP
  selector:
    app: oai-nwdaf-nbi-analytics
    project: oai-tutorial
    component: nwdaf-nbi-analytics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-nwdaf-nbi-analytics
  namespace: oai-tutorial
  labels:
    project: oai-tutorial
    component: nwdaf-nbi-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oai-nwdaf-nbi-analytics
      project: oai-tutorial
      component: nwdaf-nbi-analytics
  template:
    metadata:
      labels:
        app: oai-nwdaf-nbi-analytics
        project: oai-tutorial
        component: nwdaf-nbi-analytics
    spec:
      containers:
      - name: nbi-analytics
        image: oai-nwdaf-nbi-analytics:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8881
        env:
        - name: ENGINE_URI
          value: "http://oai-nwdaf-engine:80"
        - name: ENGINE_NUM_OF_UE_ROUTE
          value: "/network_performance/num_of_ue"
        - name: ENGINE_SESS_SUCC_RATIO_ROUTE
          value: "/network_performance/sess_succ_ratio"
        - name: ENGINE_UE_COMMUNICATION_ROUTE
          value: "/ue_communication"
        - name: ENGINE_UE_MOBILITY_ROUTE
          value: "/ue_mobility"
        - name: SERVER_ADDR
          value: "0.0.0.0:8881"
