apiVersion: v1
kind: Service
metadata:
  name: oai-nwdaf-database
  namespace: oai-tutorial
  labels:
    project: oai-tutorial
    component: nwdaf-database
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    app: oai-nwdaf-database
    project: oai-tutorial
    component: nwdaf-database
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-nwdaf-database
  namespace: oai-tutorial
  labels:
    project: oai-tutorial
    component: nwdaf-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oai-nwdaf-database
      project: oai-tutorial
      component: nwdaf-database
  template:
    metadata:
      labels:
        app: oai-nwdaf-database
        project: oai-tutorial
        component: nwdaf-database
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: "testing"
