# see: https://docs.sonarqube.org/latest/analysis/languages/python/
# set your source directory(ies) here (relative to the sonar-project.properties file)
sonar.sources=src/agent
# exclude unwanted directories and files from being analysed
# sonar.exclusions=**/test_*.py
sonar.exclusions=src/agent/ebpf/perf_ebpf_*.c
sonar.exclusions=src/agent/ebpf/ring_ebpf_*.c


# set your tests directory(ies) here (relative to the sonar-project.properties file)
# sonar.tests=src/agent/tests
# sonar.test.inclusions=**/test_*.py
sonar.cfamily.build-wrapper-output=build_wrapper_output_directory
# tests report: xUnit format
sonar.python.xunit.reportPath=src/agent/reports/TEST-*.xml
# coverage report: Cobertura format
sonar.python.coverage.reportPaths=src/agent/reports/py-coverage.cobertura.xml
# pylint: parseable format (if enabled)
sonar.python.pylint.reportPaths=src/agent/reports/py-lint.parseable.txt
# Bandit: CSV format (if enabled)
# sonar.python.bandit.reportPaths=src/agent/reports/py-bandit.bandit.csv
